# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"CONFIRMED_URI": "00_core.ipynb",
         "DEATHS_URI": "00_core.ipynb",
         "RECOVERED_URI": "00_core.ipynb",
         "confirmed_df": "00_core.ipynb",
         "deaths_df": "00_core.ipynb",
         "recovered_df": "00_core.ipynb",
         "get_data": "00_core.ipynb",
         "plot_seaborn": "00_core.ipynb",
         "generate_plots": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://jflam.github.io/covid19/"

git_url = "https://github.com/jflam/covid19/tree/master/"

def custom_doc_links(name): return None
