# AUTOGENERATED! DO NOT EDIT! File to edit: 01_dashboard.ipynb (unless otherwise specified).

__all__ = ['CONFIRMED_URI', 'DEATHS_URI', 'RECOVERED_URI', 'confirmed_df', 'deaths_df', 'recovered_df']

# Cell
#export
CONFIRMED_URI = "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv"
DEATHS_URI = "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Deaths.csv"
RECOVERED_URI = "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Recovered.csv"

import pandas as pd
confirmed_df = pd.read_csv(CONFIRMED_URI, skipinitialspace=True).fillna('')
deaths_df = pd.read_csv(DEATHS_URI, skipinitialspace=True).fillna('')
recovered_df = pd.read_csv(RECOVERED_URI, skipinitialspace=True).fillna('')