# AUTOGENERATED! DO NOT EDIT! File to edit: dashboard.ipynb (unless otherwise specified).

__all__ = ['plot_cumulative_and_daily', 'dailyConfirmedCasesColor', 'cumulativeConfirmedCasesColor']

# Cell

import datetime
import matplotlib.pyplot as plt

dailyConfirmedCasesColor = (0.1, 0.1, 0.1, 0.3)
cumulativeConfirmedCasesColor = "#1f3a93ff"

def plot_cumulative_and_daily(cum, diff, title, figure, rows, columns, index):
    # Compute the dates for the x axis of the combined plot
    dates = [datetime.datetime.strptime(d, "%Y-%m-%d").date() for d in cum.keys()]

    # Plot the bar chart of daily cases first
    ax1 = f.add_subplot(rows, columns, index)
    plt.bar(dates, diff, color=dailyConfirmedCasesColor, width=0.5)
    ax1.set_ylabel("Daily")
    xticks = ax1.get_xticks()

    # Plot the cumulative confirmed cases line chart as an overlay to the bar chart
    ax2 = plt.twinx()
    ax2.plot(dates, cum, color=cumulativeConfirmedCasesColor)
    ax2.set_ylabel("Cumulative", color=cumulativeConfirmedCasesColor)
    ax2.spines["right"].set_color(cumulativeConfirmedCasesColor)
    ax2.set_yticklabels(ax2.get_yticks(), color=cumulativeConfirmedCasesColor)
    ax2.legend(["Cumulative"])
    ax2.grid(None)

    # Format the x tick labels and add a title to the chart
    labels = [datetime.datetime.fromordinal(int(tm)).strftime("%m-%d") for tm in xticks]
    ax1.set_xticklabels(labels)
    ax1.set_title(title)